services:
  frontend:
    build: frontend/
    container_name: frontend
    stdin_open: true
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./frontend:/usr/src"
      - /usr/src/node_modules/
  backend:
    build: backend/
    container_name: backend
    ports:
      - "8080:8080"
